/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gpi;

import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author jeremy
 */
public class ConfigurationWindow extends javax.swing.JFrame {

	public MainWindow mainWindow;

	/**
	 * Creates new form ConfigurationWindow
	 */
	public ConfigurationWindow() {
		initComponents();
		this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
		this.setLocationRelativeTo(null);
	}

	/**
	 * Creates new form ConfigurationWindow
	 */
	public ConfigurationWindow(MainWindow mainWindow) {
		initComponents();
		this.mainWindow = mainWindow;
		this.jListBatiments.setModel(this.mainWindow.parcInfo.getBatiments());
		this.jListSalles.setModel(this.mainWindow.parcInfo.salles);
		this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
		this.setLocationRelativeTo(null);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonNouveauBatiment = new javax.swing.JButton();
        jButtonNouvelleSalle = new javax.swing.JButton();
        jButtonSupprimerSalle = new javax.swing.JButton();
        jButtonSupprimerBatiment = new javax.swing.JButton();
        jScrollPaneBatiments = new javax.swing.JScrollPane();
        jListBatiments = new javax.swing.JList();
        jLabelSalles = new javax.swing.JLabel();
        jLabelBatiments = new javax.swing.JLabel();
        jScrollPaneSalles = new javax.swing.JScrollPane();
        jListSalles = new javax.swing.JList();
        jButtonAssocier = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jButtonNouveauBatiment.setText("Nouveau bâtiment");
        jButtonNouveauBatiment.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonNouveauBatimentMouseClicked(evt);
            }
        });
        jButtonNouveauBatiment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNouveauBatimentActionPerformed(evt);
            }
        });

        jButtonNouvelleSalle.setText("Nouvelle salle");
        jButtonNouvelleSalle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNouvelleSalleActionPerformed(evt);
            }
        });

        jButtonSupprimerSalle.setText("Supprimer salle");
        jButtonSupprimerSalle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSupprimerSalleActionPerformed(evt);
            }
        });

        jButtonSupprimerBatiment.setText("Supprimer bâtiment");
        jButtonSupprimerBatiment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSupprimerBatimentActionPerformed(evt);
            }
        });

        jListBatiments.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jListBatiments.setName(""); // NOI18N
        jScrollPaneBatiments.setViewportView(jListBatiments);

        jLabelSalles.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelSalles.setText("Salles");
        jLabelSalles.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabelBatiments.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelBatiments.setText("Bâtiments");
        jLabelBatiments.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jListSalles.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPaneSalles.setViewportView(jListSalles);

        jButtonAssocier.setText("Associer");
        jButtonAssocier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAssocierActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPaneBatiments)
                    .addComponent(jLabelBatiments, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelSalles, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPaneSalles))
                .addGap(0, 269, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButtonNouveauBatiment, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonNouvelleSalle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonSupprimerSalle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonSupprimerBatiment)
                    .addComponent(jButtonAssocier, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(32, 32, 32))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonNouveauBatiment, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelSalles, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelBatiments, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPaneBatiments, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonNouvelleSalle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonSupprimerBatiment)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonSupprimerSalle)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonAssocier))
                    .addComponent(jScrollPaneSalles, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
		// TODO add your handling code here:
		//this.dispose();
    }//GEN-LAST:event_formWindowClosed

    private void jButtonNouveauBatimentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNouveauBatimentActionPerformed
		// TODO add your handling code here:
		String result = JOptionPane.showInputDialog("Nom du bâtiment");
		
		this.mainWindow.parcInfo.ajouterNouveauBatiment(new Batiment(result));
    }//GEN-LAST:event_jButtonNouveauBatimentActionPerformed

    private void jButtonNouveauBatimentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonNouveauBatimentMouseClicked
		// TODO add your handling code here:
    }//GEN-LAST:event_jButtonNouveauBatimentMouseClicked

    private void jButtonNouvelleSalleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNouvelleSalleActionPerformed
		// TODO add your handling code here:
		String result = JOptionPane.showInputDialog("Nom de la salle");
		this.mainWindow.parcInfo.ajouterNouvelleSalle(new Salle(result));
    }//GEN-LAST:event_jButtonNouvelleSalleActionPerformed

    private void jButtonSupprimerBatimentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSupprimerBatimentActionPerformed
        // TODO add your handling code here :
		int index = this.jListBatiments.getSelectedIndex();
		this.mainWindow.parcInfo.supprimerBatiment(index);
    }//GEN-LAST:event_jButtonSupprimerBatimentActionPerformed

    private void jButtonSupprimerSalleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSupprimerSalleActionPerformed
        // TODO add your handling code here:
		int index = this.jListSalles.getSelectedIndex();
		this.mainWindow.parcInfo.supprimerSalle(index);
    }//GEN-LAST:event_jButtonSupprimerSalleActionPerformed

    private void jButtonAssocierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAssocierActionPerformed
        // TODO add your handling code here:
		List<Salle> salles = this.jListSalles.getSelectedValuesList();
		Batiment batiment = (Batiment) this.jListBatiments.getSelectedValue();
		
		for (Salle salle : salles){
			if (!batiment.contientSalle(salle))
				batiment.ajouterNouvelleSalle(salle);
			else
				JOptionPane.showMessageDialog(this, "Cette salle est déja associée à ce bâtiment", "Le Titre", JOptionPane.ERROR_MESSAGE);
		}
    }//GEN-LAST:event_jButtonAssocierActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
		 * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(ConfigurationWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(ConfigurationWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(ConfigurationWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(ConfigurationWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new ConfigurationWindow().setVisible(true);
			}
		});
	}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAssocier;
    private javax.swing.JButton jButtonNouveauBatiment;
    private javax.swing.JButton jButtonNouvelleSalle;
    private javax.swing.JButton jButtonSupprimerBatiment;
    private javax.swing.JButton jButtonSupprimerSalle;
    private javax.swing.JLabel jLabelBatiments;
    private javax.swing.JLabel jLabelSalles;
    private javax.swing.JList jListBatiments;
    private javax.swing.JList jListSalles;
    private javax.swing.JScrollPane jScrollPaneBatiments;
    private javax.swing.JScrollPane jScrollPaneSalles;
    // End of variables declaration//GEN-END:variables
}
