/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gpi;

import java.util.Vector;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jeremy
 */
public class DetailedWindow extends javax.swing.JFrame {

	private Ordinateur ordinateur;

	/**
	 * Creates new form DetailedWindow
	 */
	public DetailedWindow(Ordinateur ordinateur) {
		initComponents();
		this.ordinateur = ordinateur;
		this.jLabelFabricantGeneralites.setText(this.jLabelFabricantGeneralites.getText() + " " + this.ordinateur.getFabriquant());
		this.jLabelModeleGeneralites.setText(this.jLabelModeleGeneralites.getText() + " " + this.ordinateur.getModele());
		this.jLabelNSerieGeneralites.setText(this.jLabelNSerieGeneralites.getText() + " " + this.ordinateur.getNumSerie());
		this.jLabelNomGeneralites.setText(this.jLabelNomGeneralites.getText() + " " + this.ordinateur.getNom());
		this.jLabelDateInstallGeneralites.setText(this.jLabelDateInstallGeneralites.getText() + " " + this.ordinateur.getDateInstall().toString());
                this.jLabelOSGeneralites.setText(this.jLabelOSGeneralites.getText() + " " + this.ordinateur.getOs().getNom());
		int nbOperations = this.ordinateur.getHistorique().size();
		System.out.println(this.ordinateur.getHistorique().size());

		if (nbOperations != 0) {
			DefaultTableModel modele = new DefaultTableModel();

			modele.addColumn(new String("Date"));
			modele.addColumn(new String("Opération"));

			for (int i = 0; i < nbOperations; i++) {
				Vector ligne = new Vector();

				ligne.add(ordinateur.getHistorique().get(i).getDate().toString());
				ligne.add(ordinateur.getHistorique().get(i).getAction());
				modele.addRow(ligne);
			}
			this.jTableHistorique.setModel(modele);
		}
	}

	/**
	 * Creates new form DetailedWindow
	 */
	public DetailedWindow() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelGeneralites = new javax.swing.JPanel();
        jLabelModeleGeneralites = new javax.swing.JLabel();
        jLabelNSerieGeneralites = new javax.swing.JLabel();
        jLabelFabricantGeneralites = new javax.swing.JLabel();
        jLabelDateInstallGeneralites = new javax.swing.JLabel();
        jLabelNomGeneralites = new javax.swing.JLabel();
        jLabelOSGeneralites = new javax.swing.JLabel();
        jPanelHistorique = new javax.swing.JPanel();
        jScrollPaneHistorique = new javax.swing.JScrollPane();
        jTableHistorique = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanelGeneralites.setBorder(javax.swing.BorderFactory.createTitledBorder("Généralités"));

        jLabelModeleGeneralites.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        jLabelModeleGeneralites.setText("Modèle :");

        jLabelNSerieGeneralites.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        jLabelNSerieGeneralites.setText("N° Série :");

        jLabelFabricantGeneralites.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        jLabelFabricantGeneralites.setText("Fabricant :");

        jLabelDateInstallGeneralites.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        jLabelDateInstallGeneralites.setText("Date d'installation :");

        jLabelNomGeneralites.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        jLabelNomGeneralites.setText("Nom :");

        jLabelOSGeneralites.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        jLabelOSGeneralites.setText("Système d'exploitation :");

        javax.swing.GroupLayout jPanelGeneralitesLayout = new javax.swing.GroupLayout(jPanelGeneralites);
        jPanelGeneralites.setLayout(jPanelGeneralitesLayout);
        jPanelGeneralitesLayout.setHorizontalGroup(
            jPanelGeneralitesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelGeneralitesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelGeneralitesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelNSerieGeneralites)
                    .addGroup(jPanelGeneralitesLayout.createSequentialGroup()
                        .addGroup(jPanelGeneralitesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelNomGeneralites)
                            .addComponent(jLabelFabricantGeneralites)
                            .addComponent(jLabelModeleGeneralites))
                        .addGap(225, 225, 225)
                        .addGroup(jPanelGeneralitesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelOSGeneralites)
                            .addComponent(jLabelDateInstallGeneralites))))
                .addContainerGap(299, Short.MAX_VALUE))
        );
        jPanelGeneralitesLayout.setVerticalGroup(
            jPanelGeneralitesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelGeneralitesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelGeneralitesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDateInstallGeneralites)
                    .addComponent(jLabelNomGeneralites))
                .addGroup(jPanelGeneralitesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelGeneralitesLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelFabricantGeneralites)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelModeleGeneralites, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelGeneralitesLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabelOSGeneralites)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelNSerieGeneralites)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jPanelHistorique.setBorder(javax.swing.BorderFactory.createTitledBorder("Historique"));

        jTableHistorique.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Date", "Opération"
            }
        ));
        jScrollPaneHistorique.setViewportView(jTableHistorique);

        javax.swing.GroupLayout jPanelHistoriqueLayout = new javax.swing.GroupLayout(jPanelHistorique);
        jPanelHistorique.setLayout(jPanelHistoriqueLayout);
        jPanelHistoriqueLayout.setHorizontalGroup(
            jPanelHistoriqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHistoriqueLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPaneHistorique, javax.swing.GroupLayout.DEFAULT_SIZE, 756, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelHistoriqueLayout.setVerticalGroup(
            jPanelHistoriqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHistoriqueLayout.createSequentialGroup()
                .addComponent(jScrollPaneHistorique, javax.swing.GroupLayout.DEFAULT_SIZE, 321, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelGeneralites, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelHistorique, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelGeneralites, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelHistorique, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
		 * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(DetailedWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(DetailedWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(DetailedWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(DetailedWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				//new DetailedWindow().setVisible(true);
			}
		});
	}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelDateInstallGeneralites;
    private javax.swing.JLabel jLabelFabricantGeneralites;
    private javax.swing.JLabel jLabelModeleGeneralites;
    private javax.swing.JLabel jLabelNSerieGeneralites;
    private javax.swing.JLabel jLabelNomGeneralites;
    private javax.swing.JLabel jLabelOSGeneralites;
    private javax.swing.JPanel jPanelGeneralites;
    private javax.swing.JPanel jPanelHistorique;
    private javax.swing.JScrollPane jScrollPaneHistorique;
    private javax.swing.JTable jTableHistorique;
    // End of variables declaration//GEN-END:variables
}
