/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gpi;

//import javax.swing.DefaultComboBoxModel;
import java.awt.FileDialog;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jeremy
 */
public class MainWindow extends javax.swing.JFrame {

	public ParcInfo parcInfo;
	public DefaultComboBoxModel<Batiment> cbm_batiments;
	public DefaultComboBoxModel<Salle> cbm_salles;

	/**
	 * Creates new form MainWindow
	 */
	public MainWindow(ParcInfo parcInfo) {

		initComponents();
		this.parcInfo = parcInfo;
		this.jComboBoxBatSupervision.setModel(this.parcInfo.getBatiments());
		this.jComboBoxSallesSupervision.setModel(this.parcInfo.getSalles());
		this.jComboBoxSalleAjoutMachine.setModel(new DefaultComboBoxModel());
		this.jComboBoxSalleAjoutMachine.addItem("Stock");
		this.setLocationRelativeTo(null);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabLvlOnglets = new javax.swing.JTabbedPane();
        jPaneRecapitulatif = new javax.swing.JPanel();
        jLabelRecapBatiment = new javax.swing.JLabel();
        jLabelRecapSalles = new javax.swing.JLabel();
        jLabelRecapOrdinateurs = new javax.swing.JLabel();
        jPanelSupervision = new javax.swing.JPanel();
        jScrollPaneTableauSupervision = new javax.swing.JScrollPane();
        jTableauSupervision = new javax.swing.JTable();
        jPanelFiltresSupervision = new javax.swing.JPanel();
        jComboBoxBatSupervision = new javax.swing.JComboBox();
        jLabelBatiments = new javax.swing.JLabel();
        jButtonFiltrerSupervision = new javax.swing.JButton();
        jLabelSallesSupervision = new javax.swing.JLabel();
        jComboBoxSallesSupervision = new javax.swing.JComboBox();
        jLabelBatiments1 = new javax.swing.JLabel();
        jComboBoxBatSupervision1 = new javax.swing.JComboBox();
        jButtonDetails = new javax.swing.JButton();
        jPanelMaintenance = new javax.swing.JPanel();
        jPanelFiltresMaintenance = new javax.swing.JPanel();
        jButtonFiltrerMaintenance = new javax.swing.JButton();
        jLabelBatimentMaintenance = new javax.swing.JLabel();
        jLabelSallesMaintenance = new javax.swing.JLabel();
        jComboBoxSallesMaintenance = new javax.swing.JComboBox();
        jComboBoxBatimentMaintenance = new javax.swing.JComboBox();
        jPanelOrdinateurMaintenance = new javax.swing.JPanel();
        jComboBoxSallesMaintance = new javax.swing.JComboBox();
        jComboBoxOrdianteurMaintenance = new javax.swing.JComboBox();
        jButtonTransfererMaintenance = new javax.swing.JButton();
        jButtonMaJMaintenance = new javax.swing.JButton();
        jLabelSalleOrdiMaintenance = new javax.swing.JLabel();
        jLabelOSOrdinateur = new javax.swing.JLabel();
        jComboBoxOSMaintenance = new javax.swing.JComboBox();
        jButtonChangerOS = new javax.swing.JButton();
        jProgressBarInstall = new javax.swing.JProgressBar();
        jLabelEtatMaintenance = new javax.swing.JLabel();
        jComboBoxStockMaintenance = new javax.swing.JComboBox();
        jPanelFabriquant = new javax.swing.JPanel();
        jTextFieldHostname = new javax.swing.JTextField();
        jLabelHostname = new javax.swing.JLabel();
        jLabelEtatAjoutMachine = new javax.swing.JLabel();
        jLabelSalleAjoutMachine = new javax.swing.JLabel();
        jLabelOSAjoutMachine = new javax.swing.JLabel();
        jComboBoxEtatAjoutMachine = new javax.swing.JComboBox();
        jComboBoxSalleAjoutMachine = new javax.swing.JComboBox();
        jScrollPaneAjoutMachine = new javax.swing.JScrollPane();
        jListOS = new javax.swing.JList();
        jButtonValiderAjoutMAchine = new javax.swing.JButton();
        jTextFieldModele = new javax.swing.JTextField();
        jLabelModele = new javax.swing.JLabel();
        jTextFieldSerial = new javax.swing.JTextField();
        jLabelSerial = new javax.swing.JLabel();
        jLabelFabriquant = new javax.swing.JLabel();
        jTextFieldFabriquant = new javax.swing.JTextField();
        jMenuBar = new javax.swing.JMenuBar();
        jMenuFichier = new javax.swing.JMenu();
        jMenuItemCharger = new javax.swing.JMenuItem();
        jMenuItemSauvegarder = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItemQuitter = new javax.swing.JMenuItem();
        jMenuOptions = new javax.swing.JMenu();
        jMenuItemConfiguration = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(810, 514));

        jLabelRecapBatiment.setText("Vous avez 0 Batiments en service ");

        jLabelRecapSalles.setText("Vous avez 0 Salles en service ");

        jLabelRecapOrdinateurs.setText("Vous avez 0 Ordinateurs dont 0 en Service, 0 en Stock et 0 en panne ");

        javax.swing.GroupLayout jPaneRecapitulatifLayout = new javax.swing.GroupLayout(jPaneRecapitulatif);
        jPaneRecapitulatif.setLayout(jPaneRecapitulatifLayout);
        jPaneRecapitulatifLayout.setHorizontalGroup(
            jPaneRecapitulatifLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPaneRecapitulatifLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPaneRecapitulatifLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelRecapBatiment, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelRecapSalles, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelRecapOrdinateurs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(385, Short.MAX_VALUE))
        );
        jPaneRecapitulatifLayout.setVerticalGroup(
            jPaneRecapitulatifLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPaneRecapitulatifLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabelRecapBatiment)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelRecapSalles)
                .addGap(8, 8, 8)
                .addComponent(jLabelRecapOrdinateurs)
                .addContainerGap(366, Short.MAX_VALUE))
        );

        jTabLvlOnglets.addTab("Récapitulatif", jPaneRecapitulatif);

        jTableauSupervision.setAutoCreateRowSorter(true);
        jTableauSupervision.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Bâtiment", "Salle", "Ordinateurs", "OS"
            }
        ));
        jScrollPaneTableauSupervision.setViewportView(jTableauSupervision);

        jPanelFiltresSupervision.setBorder(javax.swing.BorderFactory.createTitledBorder("Filtres"));
        jPanelFiltresSupervision.setToolTipText("");

        jComboBoxBatSupervision.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Tous", "TP3", "U4", "U3", "U2", "K5-Burk" }));

        jLabelBatiments.setText("Bâtiments");

        jButtonFiltrerSupervision.setText("Filtrer");
        jButtonFiltrerSupervision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFiltrerSupervisionActionPerformed(evt);
            }
        });

        jLabelSallesSupervision.setText("Salles");

        jComboBoxSallesSupervision.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Tous", "212", "210", "110" }));

        jLabelBatiments1.setText("OS");

        jComboBoxBatSupervision1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Tous", "Windows 7", "Windows 8", "Linux" }));

        javax.swing.GroupLayout jPanelFiltresSupervisionLayout = new javax.swing.GroupLayout(jPanelFiltresSupervision);
        jPanelFiltresSupervision.setLayout(jPanelFiltresSupervisionLayout);
        jPanelFiltresSupervisionLayout.setHorizontalGroup(
            jPanelFiltresSupervisionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFiltresSupervisionLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanelFiltresSupervisionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelBatiments, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelSallesSupervision, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelFiltresSupervisionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jComboBoxSallesSupervision, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBoxBatSupervision, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanelFiltresSupervisionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelFiltresSupervisionLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonFiltrerSupervision))
                    .addGroup(jPanelFiltresSupervisionLayout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jLabelBatiments1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxBatSupervision1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 328, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelFiltresSupervisionLayout.setVerticalGroup(
            jPanelFiltresSupervisionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFiltresSupervisionLayout.createSequentialGroup()
                .addGroup(jPanelFiltresSupervisionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelBatiments1)
                    .addGroup(jPanelFiltresSupervisionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jComboBoxBatSupervision, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelBatiments)
                        .addComponent(jComboBoxBatSupervision1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanelFiltresSupervisionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelFiltresSupervisionLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jButtonFiltrerSupervision))
                    .addGroup(jPanelFiltresSupervisionLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelFiltresSupervisionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBoxSallesSupervision, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelSallesSupervision))))
                .addContainerGap(6, Short.MAX_VALUE))
        );

        jButtonDetails.setText("Détails");

        javax.swing.GroupLayout jPanelSupervisionLayout = new javax.swing.GroupLayout(jPanelSupervision);
        jPanelSupervision.setLayout(jPanelSupervisionLayout);
        jPanelSupervisionLayout.setHorizontalGroup(
            jPanelSupervisionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSupervisionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelSupervisionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelFiltresSupervision, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanelSupervisionLayout.createSequentialGroup()
                        .addComponent(jButtonDetails)
                        .addGap(0, 682, Short.MAX_VALUE))
                    .addComponent(jScrollPaneTableauSupervision))
                .addContainerGap())
        );
        jPanelSupervisionLayout.setVerticalGroup(
            jPanelSupervisionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelSupervisionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelFiltresSupervision, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPaneTableauSupervision, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonDetails)
                .addGap(33, 33, 33))
        );

        jTabLvlOnglets.addTab("Supervision", jPanelSupervision);

        jPanelFiltresMaintenance.setBorder(javax.swing.BorderFactory.createTitledBorder("Filtres"));
        jPanelFiltresMaintenance.setToolTipText("");

        jButtonFiltrerMaintenance.setText("Filtrer");
        jButtonFiltrerMaintenance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFiltrerMaintenanceActionPerformed(evt);
            }
        });

        jLabelBatimentMaintenance.setText("Bâtiments");

        jLabelSallesMaintenance.setText("Salles");

        jComboBoxSallesMaintenance.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Tous", "212", "210", "110" }));

        jComboBoxBatimentMaintenance.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Tous", "TP3", "U4", "U3", "U2", "K5-Burk" }));

        javax.swing.GroupLayout jPanelFiltresMaintenanceLayout = new javax.swing.GroupLayout(jPanelFiltresMaintenance);
        jPanelFiltresMaintenance.setLayout(jPanelFiltresMaintenanceLayout);
        jPanelFiltresMaintenanceLayout.setHorizontalGroup(
            jPanelFiltresMaintenanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFiltresMaintenanceLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelFiltresMaintenanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelBatimentMaintenance, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelSallesMaintenance, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelFiltresMaintenanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jComboBoxSallesMaintenance, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBoxBatimentMaintenance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonFiltrerMaintenance)
                .addContainerGap())
        );
        jPanelFiltresMaintenanceLayout.setVerticalGroup(
            jPanelFiltresMaintenanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFiltresMaintenanceLayout.createSequentialGroup()
                .addGroup(jPanelFiltresMaintenanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelFiltresMaintenanceLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jButtonFiltrerMaintenance))
                    .addGroup(jPanelFiltresMaintenanceLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanelFiltresMaintenanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBoxBatimentMaintenance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelBatimentMaintenance))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelFiltresMaintenanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBoxSallesMaintenance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelSallesMaintenance))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelOrdinateurMaintenance.setBorder(javax.swing.BorderFactory.createTitledBorder("Ordinateur"));

        jComboBoxSallesMaintance.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "U2-211", "U2-212", "U2-213", "U3-209" }));

        jComboBoxOrdianteurMaintenance.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Dagobah", "Tatoïne", "Corruscant", "Hoth" }));

        jButtonTransfererMaintenance.setText("Transférer");

        jButtonMaJMaintenance.setText("Mettre à Jour");
        jButtonMaJMaintenance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMaJMaintenanceActionPerformed(evt);
            }
        });

        jLabelSalleOrdiMaintenance.setText("Salle");

        jLabelOSOrdinateur.setText("OS");

        jComboBoxOSMaintenance.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Windows XP", "Windows Vista", "Windows 7", "Windows 8", "Mac Os X", "Linux Debian" }));
        jComboBoxOSMaintenance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxOSMaintenanceActionPerformed(evt);
            }
        });

        jButtonChangerOS.setText("Changer l'OS");

        jProgressBarInstall.setValue(20);

        jLabelEtatMaintenance.setText("Etat");

        jComboBoxStockMaintenance.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Stock", "En Panne", "Installé" }));

        javax.swing.GroupLayout jPanelOrdinateurMaintenanceLayout = new javax.swing.GroupLayout(jPanelOrdinateurMaintenance);
        jPanelOrdinateurMaintenance.setLayout(jPanelOrdinateurMaintenanceLayout);
        jPanelOrdinateurMaintenanceLayout.setHorizontalGroup(
            jPanelOrdinateurMaintenanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelOrdinateurMaintenanceLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelOrdinateurMaintenanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelSalleOrdiMaintenance)
                    .addComponent(jLabelEtatMaintenance)
                    .addComponent(jLabelOSOrdinateur))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelOrdinateurMaintenanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jProgressBarInstall, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanelOrdinateurMaintenanceLayout.createSequentialGroup()
                        .addGroup(jPanelOrdinateurMaintenanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBoxStockMaintenance, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBoxSallesMaintance, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBoxOrdianteurMaintenance, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBoxOSMaintenance, 0, 0, Short.MAX_VALUE))
                        .addGroup(jPanelOrdinateurMaintenanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelOrdinateurMaintenanceLayout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(jButtonChangerOS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelOrdinateurMaintenanceLayout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addGroup(jPanelOrdinateurMaintenanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButtonTransfererMaintenance, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButtonMaJMaintenance, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addContainerGap())
        );
        jPanelOrdinateurMaintenanceLayout.setVerticalGroup(
            jPanelOrdinateurMaintenanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelOrdinateurMaintenanceLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelOrdinateurMaintenanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxOrdianteurMaintenance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonMaJMaintenance))
                .addGap(18, 18, 18)
                .addGroup(jPanelOrdinateurMaintenanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonTransfererMaintenance)
                    .addComponent(jComboBoxSallesMaintance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelSalleOrdiMaintenance))
                .addGap(8, 8, 8)
                .addGroup(jPanelOrdinateurMaintenanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelOrdinateurMaintenanceLayout.createSequentialGroup()
                        .addComponent(jLabelEtatMaintenance)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelOrdinateurMaintenanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonChangerOS)
                            .addComponent(jLabelOSOrdinateur)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelOrdinateurMaintenanceLayout.createSequentialGroup()
                        .addComponent(jComboBoxStockMaintenance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jComboBoxOSMaintenance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jProgressBarInstall, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE))
        );

        jPanelFabriquant.setBorder(javax.swing.BorderFactory.createTitledBorder("Ajout Machine"));

        jLabelHostname.setText("Nom d'hote");

        jLabelEtatAjoutMachine.setText("Etat");

        jLabelSalleAjoutMachine.setText("Salle");

        jLabelOSAjoutMachine.setText("OS");

        jComboBoxEtatAjoutMachine.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Stock", "En Panne", "Installé" }));
        jComboBoxEtatAjoutMachine.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxEtatAjoutMachineItemStateChanged(evt);
            }
        });

        jListOS.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Windows XP", "Windows Vista", "Windows 7", "Windows 8", "Mac Os X", "Linux Debian" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPaneAjoutMachine.setViewportView(jListOS);

        jButtonValiderAjoutMAchine.setText("Valider");
        jButtonValiderAjoutMAchine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonValiderAjoutMAchineActionPerformed(evt);
            }
        });

        jLabelModele.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelModele.setText("Modèle");

        jLabelSerial.setText("N° de Serie");

        jLabelFabriquant.setText("Fabriquant");

        jTextFieldFabriquant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldFabriquantActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelFabriquantLayout = new javax.swing.GroupLayout(jPanelFabriquant);
        jPanelFabriquant.setLayout(jPanelFabriquantLayout);
        jPanelFabriquantLayout.setHorizontalGroup(
            jPanelFabriquantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFabriquantLayout.createSequentialGroup()
                .addGroup(jPanelFabriquantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelFabriquantLayout.createSequentialGroup()
                        .addGroup(jPanelFabriquantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelFabriquantLayout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(jLabelHostname))
                            .addGroup(jPanelFabriquantLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanelFabriquantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelFabriquant)
                                    .addComponent(jLabelModele)))
                            .addGroup(jPanelFabriquantLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabelSerial)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelFabriquantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldFabriquant)
                            .addComponent(jTextFieldSerial, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextFieldModele)
                            .addComponent(jTextFieldHostname)))
                    .addGroup(jPanelFabriquantLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanelFabriquantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelEtatAjoutMachine)
                            .addComponent(jLabelOSAjoutMachine)
                            .addComponent(jLabelSalleAjoutMachine))
                        .addGap(54, 54, 54)
                        .addGroup(jPanelFabriquantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBoxSalleAjoutMachine, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBoxEtatAjoutMachine, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPaneAjoutMachine, javax.swing.GroupLayout.DEFAULT_SIZE, 341, Short.MAX_VALUE)
                            .addComponent(jButtonValiderAjoutMAchine, javax.swing.GroupLayout.DEFAULT_SIZE, 341, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanelFabriquantLayout.setVerticalGroup(
            jPanelFabriquantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFabriquantLayout.createSequentialGroup()
                .addGroup(jPanelFabriquantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldHostname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelHostname))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelFabriquantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldFabriquant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelFabriquant))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelFabriquantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldModele, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelModele))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelFabriquantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelSerial)
                    .addComponent(jTextFieldSerial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelFabriquantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelEtatAjoutMachine, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelFabriquantLayout.createSequentialGroup()
                        .addComponent(jComboBoxEtatAjoutMachine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelFabriquantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBoxSalleAjoutMachine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelSalleAjoutMachine))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelFabriquantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPaneAjoutMachine, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelOSAjoutMachine))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonValiderAjoutMAchine)
                .addContainerGap(6, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelMaintenanceLayout = new javax.swing.GroupLayout(jPanelMaintenance);
        jPanelMaintenance.setLayout(jPanelMaintenanceLayout);
        jPanelMaintenanceLayout.setHorizontalGroup(
            jPanelMaintenanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMaintenanceLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelMaintenanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanelOrdinateurMaintenance, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelFiltresMaintenance, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jPanelFabriquant, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelMaintenanceLayout.setVerticalGroup(
            jPanelMaintenanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMaintenanceLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelMaintenanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanelFabriquant, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanelMaintenanceLayout.createSequentialGroup()
                        .addComponent(jPanelFiltresMaintenance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanelOrdinateurMaintenance, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabLvlOnglets.addTab("Maintenance", jPanelMaintenance);

        jMenuFichier.setText("Fichier");

        jMenuItemCharger.setText("Charger");
        jMenuItemCharger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemChargerActionPerformed(evt);
            }
        });
        jMenuFichier.add(jMenuItemCharger);

        jMenuItemSauvegarder.setText("Sauvegarder");
        jMenuItemSauvegarder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSauvegarderActionPerformed(evt);
            }
        });
        jMenuFichier.add(jMenuItemSauvegarder);
        jMenuFichier.add(jSeparator1);

        jMenuItemQuitter.setText("Quitter");
        jMenuItemQuitter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemQuitterActionPerformed(evt);
            }
        });
        jMenuFichier.add(jMenuItemQuitter);

        jMenuBar.add(jMenuFichier);

        jMenuOptions.setText("Options");

        jMenuItemConfiguration.setText("Configuration");
        jMenuItemConfiguration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemConfigurationActionPerformed(evt);
            }
        });
        jMenuOptions.add(jMenuItemConfiguration);

        jMenuBar.add(jMenuOptions);

        setJMenuBar(jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabLvlOnglets)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabLvlOnglets)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonMaJMaintenanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMaJMaintenanceActionPerformed
		// TODO add your handling code here:
    }//GEN-LAST:event_jButtonMaJMaintenanceActionPerformed

    private void jButtonFiltrerMaintenanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFiltrerMaintenanceActionPerformed
		// TODO add your handling code here:
    }//GEN-LAST:event_jButtonFiltrerMaintenanceActionPerformed

    private void jButtonFiltrerSupervisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFiltrerSupervisionActionPerformed
		// TODO add your handling code here:
		DefaultTableModel modele = new DefaultTableModel();

		modele.addColumn(new String("Bâtiments"));
		modele.addColumn(new String("Salles"));
		modele.addColumn(new String("Ordinateurs"));
		modele.addColumn(new String("OS"));

		int nbBatiments = this.parcInfo.getBatiments().getSize();
		System.out.println("nbBatiments : " + nbBatiments);

		// Pour tous les batiments
		for (int i = 0; i < nbBatiments; i++) {
			Vector ligne = null;
			Batiment batiment = null;
			batiment = (Batiment) this.parcInfo.getBatiments().getElementAt(i);
			int nbSalles = batiment.getSalles().getSize();

			// Si le bâtiment a au moins 1 salle
			if (nbSalles > 0) {
				// Pour toutes les salles du batiment
				for (int j = 0; j < nbSalles; j++) {
					Salle salle = (Salle) batiment.getSalles().getElementAt(j);

					int nbOrdinateurs = salle.getOrdinateurs().getSize();

					if (nbOrdinateurs > 0) {
						for (int k = 0; k < nbOrdinateurs; k++) {
							Ordinateur ordinateur = (Ordinateur) salle.getOrdinateurs().getElementAt(k);

							ligne = new Vector();

							ligne.add(batiment);
							ligne.add(salle);
							ligne.add(ordinateur);
							modele.addRow(ligne);
						}
					}

					if (nbOrdinateurs == 0) {
						ligne = new Vector();

						ligne.add(batiment);
						ligne.add(salle);
						modele.addRow(ligne);
					}
				}
			} else {
				ligne = new Vector();

				ligne.add(batiment);
				modele.addRow(ligne);
			}
		}
		this.jTableauSupervision.setModel(modele);
    }//GEN-LAST:event_jButtonFiltrerSupervisionActionPerformed

    private void jComboBoxOSMaintenanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxOSMaintenanceActionPerformed
		// TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxOSMaintenanceActionPerformed

    private void jButtonValiderAjoutMAchineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonValiderAjoutMAchineActionPerformed
		// TODO add your handling code here:
		Ordinateur ordinateur = new Ordinateur(this.jTextFieldHostname.getText(), this.jTextFieldModele.getText(), this.jTextFieldFabriquant.getText(), this.jTextFieldSerial.getText());
		String NomOS = this.jComboBoxOSMaintenance.getSelectedItem().toString();
		OS os = new OS();
		DefaultComboBoxModel<OS> modele = new DefaultComboBoxModel();
		modele.addElement(os);
		ordinateur.setOs(modele);
		ordinateur.setEtat(this.jComboBoxEtatAjoutMachine.getSelectedItem().toString());

		if (this.jComboBoxEtatAjoutMachine.getSelectedItem().toString() == "Stock") {
			this.parcInfo.ajouterNouvelOrdinateur(ordinateur, ((Salle) this.parcInfo.getSalles().getElementAt(0)));
		} else {
			Salle salle = (Salle) this.jComboBoxSalleAjoutMachine.getSelectedItem();
			this.parcInfo.ajouterNouvelOrdinateur(ordinateur, salle);
		}
    }//GEN-LAST:event_jButtonValiderAjoutMAchineActionPerformed

    private void jTextFieldFabriquantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldFabriquantActionPerformed
		// TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldFabriquantActionPerformed

    private void jComboBoxEtatAjoutMachineItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxEtatAjoutMachineItemStateChanged
		// TODO add your handling code here:
		if (this.jComboBoxEtatAjoutMachine.getSelectedItem().toString() == "Stock") {
			this.jComboBoxSalleAjoutMachine.setModel(new DefaultComboBoxModel());
			this.jComboBoxSalleAjoutMachine.addItem("Stock");
		} else {
			this.jComboBoxSalleAjoutMachine.setModel(this.parcInfo.getSalles());
		}
    }//GEN-LAST:event_jComboBoxEtatAjoutMachineItemStateChanged

    private void jMenuItemChargerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemChargerActionPerformed
		// TODO add your handling code here:
		FileDialog fileDialog = new FileDialog(this, "Choix du fichier à charger", FileDialog.LOAD);
		fileDialog.setVisible(true);
		String fichier = fileDialog.getDirectory() + fileDialog.getFile();
		System.out.println(fichier);
		this.parcInfo = null;
		this.parcInfo = Sauvegarde.charger(fichier);
    }//GEN-LAST:event_jMenuItemChargerActionPerformed

    private void jMenuItemSauvegarderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSauvegarderActionPerformed
		// TODO add your handling code here:
		FileDialog fileDialog = new FileDialog(this, "Choix du fichier à sauvegarder", FileDialog.SAVE);
		fileDialog.setVisible(true);
		String fichier = fileDialog.getDirectory() + fileDialog.getFile();
		Sauvegarde.sauvegarder(this.parcInfo, fichier);
    }//GEN-LAST:event_jMenuItemSauvegarderActionPerformed

    private void jMenuItemConfigurationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemConfigurationActionPerformed
        // TODO add your handling code here:
		ConfigurationWindow configuration = new ConfigurationWindow(this);
		configuration.setVisible(true);
    }//GEN-LAST:event_jMenuItemConfigurationActionPerformed

    private void jMenuItemQuitterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemQuitterActionPerformed
        // TODO add your handling code here:
		System.exit(0);
    }//GEN-LAST:event_jMenuItemQuitterActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
		 * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {


			javax.swing.UIManager.setLookAndFeel(javax.swing.UIManager.getSystemLookAndFeelClassName());



		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>*/

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				//new MainWindow().setVisible(true);
			}
		});
	}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonChangerOS;
    private javax.swing.JButton jButtonDetails;
    private javax.swing.JButton jButtonFiltrerMaintenance;
    private javax.swing.JButton jButtonFiltrerSupervision;
    private javax.swing.JButton jButtonMaJMaintenance;
    private javax.swing.JButton jButtonTransfererMaintenance;
    private javax.swing.JButton jButtonValiderAjoutMAchine;
    private javax.swing.JComboBox jComboBoxBatSupervision;
    private javax.swing.JComboBox jComboBoxBatSupervision1;
    private javax.swing.JComboBox jComboBoxBatimentMaintenance;
    private javax.swing.JComboBox jComboBoxEtatAjoutMachine;
    private javax.swing.JComboBox jComboBoxOSMaintenance;
    private javax.swing.JComboBox jComboBoxOrdianteurMaintenance;
    private javax.swing.JComboBox jComboBoxSalleAjoutMachine;
    private javax.swing.JComboBox jComboBoxSallesMaintance;
    private javax.swing.JComboBox jComboBoxSallesMaintenance;
    private javax.swing.JComboBox jComboBoxSallesSupervision;
    private javax.swing.JComboBox jComboBoxStockMaintenance;
    private javax.swing.JLabel jLabelBatimentMaintenance;
    private javax.swing.JLabel jLabelBatiments;
    private javax.swing.JLabel jLabelBatiments1;
    private javax.swing.JLabel jLabelEtatAjoutMachine;
    private javax.swing.JLabel jLabelEtatMaintenance;
    private javax.swing.JLabel jLabelFabriquant;
    private javax.swing.JLabel jLabelHostname;
    private javax.swing.JLabel jLabelModele;
    private javax.swing.JLabel jLabelOSAjoutMachine;
    private javax.swing.JLabel jLabelOSOrdinateur;
    private javax.swing.JLabel jLabelRecapBatiment;
    private javax.swing.JLabel jLabelRecapOrdinateurs;
    private javax.swing.JLabel jLabelRecapSalles;
    private javax.swing.JLabel jLabelSalleAjoutMachine;
    private javax.swing.JLabel jLabelSalleOrdiMaintenance;
    private javax.swing.JLabel jLabelSallesMaintenance;
    private javax.swing.JLabel jLabelSallesSupervision;
    private javax.swing.JLabel jLabelSerial;
    private javax.swing.JList jListOS;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JMenu jMenuFichier;
    private javax.swing.JMenuItem jMenuItemCharger;
    private javax.swing.JMenuItem jMenuItemConfiguration;
    private javax.swing.JMenuItem jMenuItemQuitter;
    private javax.swing.JMenuItem jMenuItemSauvegarder;
    private javax.swing.JMenu jMenuOptions;
    private javax.swing.JPanel jPaneRecapitulatif;
    private javax.swing.JPanel jPanelFabriquant;
    private javax.swing.JPanel jPanelFiltresMaintenance;
    private javax.swing.JPanel jPanelFiltresSupervision;
    private javax.swing.JPanel jPanelMaintenance;
    private javax.swing.JPanel jPanelOrdinateurMaintenance;
    private javax.swing.JPanel jPanelSupervision;
    private javax.swing.JProgressBar jProgressBarInstall;
    private javax.swing.JScrollPane jScrollPaneAjoutMachine;
    private javax.swing.JScrollPane jScrollPaneTableauSupervision;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JTabbedPane jTabLvlOnglets;
    private javax.swing.JTable jTableauSupervision;
    private javax.swing.JTextField jTextFieldFabriquant;
    private javax.swing.JTextField jTextFieldHostname;
    private javax.swing.JTextField jTextFieldModele;
    private javax.swing.JTextField jTextFieldSerial;
    // End of variables declaration//GEN-END:variables
}
